name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.0
          run_install: false

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm config set node-linker hoisted
          pnpm install --frozen-lockfile --no-verify-store-integrity

      # - name: Build workspace
      #   run: |
      #     pnpm nx run-many --target=build --all

      # - name: Run lint and test
      #   run: |
      #     pnpm nx run-many --target=lint --all
      #     pnpm nx run-many --target=test --all
